services:
  #  one-time sidecar to set volume permissions to 1000:100
  volume-manager:
    command: chown -R 1000:1000 /data
    container_name: volume-manager
    image: alpine@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
    user: root:root # runs as root to match Docker daemon for volume management
    volumes:
      - todo.data:/data

  todo:
    container_name: todo
    depends_on:
      volume-manager:
        condition: service_completed_successfully
    image: nickfedor/todo:latest-amd64
    # image: ghcr.io/nicholas-fedor/todo:latest
    volumes:
      - todo.data:/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    security_opt:
      - "no-new-privileges=true"

volumes:
  todo.data:
