name: Lint GitHub Actions workflows

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: nicholas-fedor/actionlint-action@a613712cf8a5fd5c8477218429f620e5e29fa679 # v1.0.9
