name: Run tests and upload coverage

on:
  workflow_call:
  pull_request:
    paths:
      - cmd/**
      - internal/**
      - go.mod
      - go.sum
      - main.go

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: |
            go.mod
            **/go.sum

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@5ddd784440b232930161d76c7ca85d922fdcf183 # v0.3.1001

      - name: Install dependencies
        run: go mod download

      - name: Generate templates
        run: templ generate ./...

      - name: Run tests
        run: |
          go test -race -v -coverprofile coverage.out -covermode atomic ./...
